"""add unidades_gerenciais

Revision ID: 7d4d4a15617b
Revises: a05988ccdc3e
Create Date: 2025-10-25 00:53:41.145025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d4d4a15617b'
down_revision: Union[str, Sequence[str], None] = 'a05988ccdc3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Verificar se a tabela já existe
    connection = op.get_bind()
    result = connection.execute(sa.text("""
        SELECT EXISTS (
            SELECT FROM information_schema.tables 
            WHERE table_schema = 'public' 
            AND table_name = 'unidades_gerenciais'
        )
    """))
    table_exists = result.scalar()
    
    if not table_exists:
        op.create_table('unidades_gerenciais',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('codigo', sa.String(length=64), nullable=False),
        sa.Column('nome', sa.String(length=255), nullable=False),
        sa.Column('tipo_unidade', sa.String(length=32), nullable=False),
        sa.Column('nivel_hierarquico', sa.String(length=64), nullable=False),
        sa.Column('empresa_id', sa.Integer(), nullable=False),
        sa.Column('responsavel_id', sa.Integer(), nullable=True),
        sa.Column('ug_superior_id', sa.Integer(), nullable=True),
        sa.Column('status', sa.String(length=32), nullable=False),
        sa.Column('data_criacao', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('data_atualizacao', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['empresa_id'], ['companies.id'], ),
        sa.ForeignKeyConstraint(['responsavel_id'], ['employees.id'], ),
        sa.ForeignKeyConstraint(['ug_superior_id'], ['unidades_gerenciais.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_unidades_gerenciais_codigo'), 'unidades_gerenciais', ['codigo'], unique=True)
        op.create_index(op.f('ix_unidades_gerenciais_empresa_id'), 'unidades_gerenciais', ['empresa_id'], unique=False)
        op.create_index(op.f('ix_unidades_gerenciais_id'), 'unidades_gerenciais', ['id'], unique=False)
        op.create_index(op.f('ix_unidades_gerenciais_responsavel_id'), 'unidades_gerenciais', ['responsavel_id'], unique=False)
        op.create_index(op.f('ix_unidades_gerenciais_ug_superior_id'), 'unidades_gerenciais', ['ug_superior_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unidades_gerenciais_ug_superior_id'), table_name='unidades_gerenciais')
    op.drop_index(op.f('ix_unidades_gerenciais_responsavel_id'), table_name='unidades_gerenciais')
    op.drop_index(op.f('ix_unidades_gerenciais_id'), table_name='unidades_gerenciais')
    op.drop_index(op.f('ix_unidades_gerenciais_empresa_id'), table_name='unidades_gerenciais')
    op.drop_index(op.f('ix_unidades_gerenciais_codigo'), table_name='unidades_gerenciais')
    op.drop_table('unidades_gerenciais')
    # ### end Alembic commands ###
