"""add employees

Revision ID: a05988ccdc3e
Revises: fc1841cf5304
Create Date: 2025-10-24 22:51:31.970534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a05988ccdc3e'
down_revision: Union[str, Sequence[str], None] = 'fc1841cf5304'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Criar enums apenas se não existirem (usando DO block do PostgreSQL)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE vinculo_enum AS ENUM ('proprio', 'terceiro', 'temporario');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)
    
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE status_enum AS ENUM ('ativo', 'inativo');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)
    
    # Verificar se a tabela employees já existe
    connection = op.get_bind()
    result = connection.execute(sa.text("""
        SELECT EXISTS (
            SELECT FROM information_schema.tables 
            WHERE table_schema = 'public' 
            AND table_name = 'employees'
        )
    """))
    table_exists = result.scalar()
    
    if not table_exists:
        op.create_table('employees',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('full_name', sa.String(length=255), nullable=False),
        sa.Column('cpf', sa.String(length=14), nullable=False),
        sa.Column('matricula', sa.String(length=64), nullable=True),
        sa.Column('cargo_funcao', sa.String(length=255), nullable=True),
        sa.Column('empresa_id', sa.Integer(), nullable=False),
        sa.Column('ug_id', sa.Integer(), nullable=True),
        sa.Column('centro_custo_id', sa.Integer(), nullable=True),
        sa.Column('tipo_vinculo', sa.Enum('proprio', 'terceiro', 'temporario', name='vinculo_enum', create_type=False), nullable=False),
        sa.Column('data_admissao', sa.Date(), nullable=False),
        sa.Column('data_desligamento', sa.Date(), nullable=True),
        sa.Column('telefone', sa.String(length=32), nullable=True),
        sa.Column('email_corporativo', sa.String(length=255), nullable=True),
        sa.Column('endereco', sa.String(length=255), nullable=True),
        sa.Column('cidade', sa.String(length=255), nullable=True),
        sa.Column('estado', sa.String(length=32), nullable=True),
        sa.Column('status', sa.Enum('ativo', 'inativo', name='status_enum', create_type=False), nullable=False),
        sa.Column('observacoes', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['empresa_id'], ['companies.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_employees_cpf'), 'employees', ['cpf'], unique=False)
        op.create_index(op.f('ix_employees_empresa_id'), 'employees', ['empresa_id'], unique=False)
        op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_empresa_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_cpf'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
