"""Add classes and contas contabeis

Revision ID: f05090aaded8
Revises: bf5edff61642
Create Date: 2026-02-01 17:22:58.391005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f05090aaded8'
down_revision: Union[str, Sequence[str], None] = 'bf5edff61642'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Classes Contabeis changes
    op.add_column('classes_contabeis', sa.Column('vida_util_anos', sa.Integer(), nullable=False))
    op.add_column('classes_contabeis', sa.Column('taxa_depreciacao', sa.Numeric(precision=5, scale=2), nullable=False))
    op.add_column('classes_contabeis', sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    
    # Drop old constraints/columns
    # Note: Using names from autogen
    op.drop_index(op.f('ix_classes_contabeis_conta_contabil_id'), table_name='classes_contabeis')
    op.drop_constraint('uq_classe_empresa', 'classes_contabeis', type_='unique')
    op.drop_constraint('classes_contabeis_conta_contabil_id_fkey', 'classes_contabeis', type_='foreignkey')
    op.drop_column('classes_contabeis', 'conta_contabil_id')
    op.drop_column('classes_contabeis', 'observacoes')
    
    op.create_index(op.f('ix_classes_contabeis_codigo'), 'classes_contabeis', ['codigo'], unique=True)
    
    # Contas Contabeis changes
    op.add_column('contas_contabeis', sa.Column('codigo', sa.String(length=50), nullable=False))
    op.add_column('contas_contabeis', sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    
    # Drop old constraints/columns
    op.drop_constraint('uq_conta_empresa', 'contas_contabeis', type_='unique')
    op.drop_column('contas_contabeis', 'conta')
    op.drop_column('contas_contabeis', 'observacoes')
    
    op.create_index(op.f('ix_contas_contabeis_codigo'), 'contas_contabeis', ['codigo'], unique=True)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Revert Contas Contabeis
    op.drop_index(op.f('ix_contas_contabeis_codigo'), table_name='contas_contabeis')
    op.add_column('contas_contabeis', sa.Column('observacoes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('contas_contabeis', sa.Column('conta', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_unique_constraint('uq_conta_empresa', 'contas_contabeis', ['empresa_id', 'conta'])
    op.drop_column('contas_contabeis', 'criado_em')
    op.drop_column('contas_contabeis', 'codigo')

    # Revert Classes Contabeis
    op.drop_index(op.f('ix_classes_contabeis_codigo'), table_name='classes_contabeis')
    op.add_column('classes_contabeis', sa.Column('observacoes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('classes_contabeis', sa.Column('conta_contabil_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('classes_contabeis_conta_contabil_id_fkey', 'classes_contabeis', 'contas_contabeis', ['conta_contabil_id'], ['id'])
    op.create_unique_constraint('uq_classe_empresa', 'classes_contabeis', ['empresa_id', 'codigo'])
    op.create_index('ix_classes_contabeis_conta_contabil_id', 'classes_contabeis', ['conta_contabil_id'], unique=False)
    op.drop_column('classes_contabeis', 'criado_em')
    op.drop_column('classes_contabeis', 'taxa_depreciacao')
    op.drop_column('classes_contabeis', 'vida_util_anos')
    
    # ### end Alembic commands ###
